# Generated by Django 5.1.6 on 2025-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainaccount',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='mainaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
